# Generated by Django 5.1.2 on 2024-10-24 15:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 15, 39, 26, 364852, tzinfo=datetime.timezone.utc)),
        ),
    ]
